### ISSUE TITLE
cortex_plugin.dart error

### ISSUE THREAD

**Issue by Dr-Faxzty** [Emotiv/flutter-plugin#2]
when i run debug it show me this error:
════════ Exception caught by services library ══════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel dev.emotiv.cortex/response:
MissingPluginException(No implementation found for method listen on channel dev.emotiv.cortex/response)

can someone tell me why?

**Comment by nguoithichkhampha** [comment]
@Dr-Faxzty , when do you get this error ? in building step or running step ?
Note that, to run in a mobile application, you need to add our cortex mobile library. Pls read 
https://github.com/Emotiv/flutter-plugin/tree/main/packages/cortex#attention
